name: qoxaria
description: "A downloader and launcher for Qoxaria Minecraft server."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.2+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  path_provider: ^2.1.5
  logging: ^1.3.0
  url_launcher: ^6.3.1
  dotenv: ^4.2.0
  archive: ^3.6.1
  file_picker: ^8.1.4
  toastification: ^2.3.0
  window_size: ^0.1.0
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  msix: ^3.16.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true

  assets:
    - assets/

msix_config:
  display_name: Qoxaria
  publisher_display_name: Buffones
  identity_name: Buffones.Qoxaria
  publisher: CN=55B1E00F-E444-4FCE-BB2C-7C607F87C39A
  msix_version: 0.0.2.0
  logo_path: assets\icon.ico
  capabilities: internetClient
